apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: reviews
    descriptors:
      - key: PATH
        value: "/productpage"
        rate_limit:
          unit: second
          requests_per_unit: 1